name = "ChemicalReactionNetworks"
uuid = "b20ad514-df08-11e8-170c-d7c9d0550834"
authors = ["anj1 <alireza.n.j@gmail.com>"]
version = "0.1.0"

[deps]
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
